\ fsoc/toolchains/quartus.4th — emit .qsf .sdc build.sh load.sh

variable qsf-buf
variable qsf-len
variable q-dir-a
variable q-dir-u

: qsf-put ( c-addr u - )
    qsf-buf @ qsf-len @ 2swap fsoc-append
    qsf-buf @ qsf-len @ fsoc-str-free
    qsf-len ! qsf-buf ! ;

: qsf-nl ( - ) s\" \n" qsf-put ;

: quartus-emit-plain-io ( io - )
    s" set_location_assignment PIN_" qsf-put
    dup io.pins$ @ fsoc-fetch qsf-put
    s"  -to " qsf-put
    io.name$ @ fsoc-fetch qsf-put
    qsf-nl ;

: quartus-emit-subs ( io - )
    io.subs @ ulist-head @
    begin dup while
        dup >r unode-addr @
        s" set_location_assignment PIN_" qsf-put
        dup sub.pins$ @ fsoc-fetch qsf-put
        s"  -to " qsf-put
        sub.name$ @ fsoc-fetch qsf-put
        qsf-nl
        r> unode-next @
    repeat drop ;

: quartus-emit-io ( io - )
    dup io.subs @ ulist-len 0= IF
        quartus-emit-plain-io
    ELSE
        quartus-emit-subs
    THEN ;

: quartus-emit-req ( req - )
    req.io @ quartus-emit-io ;

: quartus-qsf-build ( - c-addr u )
    s" # generated by fsoc" fsoc-str-dup qsf-len ! qsf-buf !
    qsf-nl
    s" set_global_assignment -name FAMILY Cyclone IV E" qsf-put qsf-nl
    s" set_global_assignment -name DEVICE " qsf-put
    plat.device@ qsf-put qsf-nl
    s" set_global_assignment -name TOP_LEVEL_ENTITY blinky" qsf-put qsf-nl
    s" set_global_assignment -name VERILOG_FILE blinky.v" qsf-put qsf-nl
    plat@ plat.reqs @ ulist-head @
    begin dup while
        dup >r unode-addr @ quartus-emit-req
        r> unode-next @
    repeat drop
    qsf-buf @ qsf-len @ ;

: quartus-join ( c-addr-dir u c-addr-name u - c-addr u )
    fsoc-append ;

: quartus-emit ( c-addr-dir u - )
    q-dir-u ! q-dir-a !
    q-dir-a @ q-dir-u @ s" /blinky.qsf" quartus-join
    quartus-qsf-build fsoc-write-file
    q-dir-a @ q-dir-u @ s" /blinky.sdc" quartus-join
    s\" create_clock -name clk50 -period 20.000 [get_ports {clk50}]\n"
    fsoc-write-file
    q-dir-a @ q-dir-u @ s" /build.sh" quartus-join
    s\" #!/bin/sh\nset -e\nquartus_map blinky\nquartus_fit blinky\nquartus_asm blinky\necho quartus build done\n"
    fsoc-write-file
    q-dir-a @ q-dir-u @ s" /load.sh" quartus-join
    s\" #!/bin/sh\nset -e\nquartus_pgm -m jtag -o p;blinky.sof\n"
    fsoc-write-file ;
