// CD16 core on the package balls. Stack RAM is inside; program and data
// buses are pins. The stack read is same-cycle in the original, so the
// block RAM is clocked at twice the CPU clock: write on the edge aligned
// with the CPU, read on the edge halfway through the cycle.
// https://web.archive.org/web/20060714230040/http://tinyboot.com/cd16/cd16v13.zip
`default_nettype none
`include "cd16.v"

// 25 MHz in, 50 MHz and 25 MHz out, generated by ecppll.
module cd16_pll (
    input  wire clkin,
    output wire clk50,
    output wire clk25,
    output wire locked
);
    wire clkfb;
    (* FREQUENCY_PIN_CLKI="25" *)
    (* FREQUENCY_PIN_CLKOP="50" *)
    (* FREQUENCY_PIN_CLKOS="25" *)
    (* ICP_CURRENT="12" *) (* LPF_RESISTOR="8" *)
    (* MFG_ENABLE_FILTEROPAMP="1" *) (* MFG_GMCREF_SEL="2" *)
    EHXPLLL #(
        .PLLRST_ENA("DISABLED"),
        .INTFB_WAKE("DISABLED"),
        .STDBY_ENABLE("DISABLED"),
        .DPHASE_SOURCE("DISABLED"),
        .OUTDIVIDER_MUXA("DIVA"),
        .OUTDIVIDER_MUXB("DIVB"),
        .OUTDIVIDER_MUXC("DIVC"),
        .OUTDIVIDER_MUXD("DIVD"),
        .CLKI_DIV(1),
        .CLKOP_ENABLE("ENABLED"),
        .CLKOP_DIV(12),
        .CLKOP_CPHASE(5),
        .CLKOP_FPHASE(0),
        .CLKOS_ENABLE("ENABLED"),
        .CLKOS_DIV(24),
        .CLKOS_CPHASE(5),
        .CLKOS_FPHASE(0),
        .FEEDBK_PATH("INT_OP"),
        .CLKFB_DIV(2)
    ) pll_i (
        .RST(1'b0),
        .STDBY(1'b0),
        .CLKI(clkin),
        .CLKOP(clk50),
        .CLKOS(clk25),
        .CLKOS2(),
        .CLKOS3(),
        .CLKFB(clkfb),
        .CLKINTFB(clkfb),
        .PHASESEL0(1'b0),
        .PHASESEL1(1'b0),
        .PHASEDIR(1'b1),
        .PHASESTEP(1'b1),
        .PHASELOADREG(1'b1),
        .PLLWAKESYNC(1'b0),
        .ENCLKOP(1'b0),
        .LOCK(locked),
        .ENCLKOS(1'b0),
        .ENCLKOS2(1'b0),
        .ENCLKOS3(1'b0),
        .INTLOCK(),
        .REFCLK()
    );
endmodule

module top (
    input  wire        clk,
    input  wire        reset,
    input  wire        hold,
    input  wire [6:0]  int,
    input  wire [15:0] pi,
    input  wire [15:0] di,
    output wire [15:0] py,
    output wire [15:0] pa,
    output wire [5:0]  pbank,
    output wire        wp,
    output wire [15:0] dy,
    output wire [15:0] da,
    output wire        wd,
    output wire        rd
);
    wire clk50, clk25, locked;
    wire cpu_reset = reset | ~locked;

    cd16_pll gen (
        .clkin(clk),
        .clk50(clk50),
        .clk25(clk25),
        .locked(locked)
    );

    // half is 1 on the mid-cycle RAM edge and 0 on the CPU edge.
    // clk25 is data here: the two PLL outputs share an edge.
    reg half;
    always @(negedge clk50)
        half <= clk25;

    wire [15:0] ia, ib, ya, yb;
    wire [7:0]  aa, ab;
    wire        wa, wb, ra, rb;
    wire        we_a = wa & ~half;
    wire        we_b = wb & ~half;
    wire [17:0] dia = {2'b00, ia};
    wire [17:0] dib = {2'b00, ib};
    wire [17:0] doa, dob;
    assign ya = doa[15:0];
    assign yb = dob[15:0];

    // 1024 x 18, low 256 words, low 16 bits. ADA[1:0] are the byte
    // write enables in this mode; the address is ADA[11:4].
    DP16KD #(
        .DATA_WIDTH_A(18),
        .DATA_WIDTH_B(18),
        .REGMODE_A("NOREG"),
        .REGMODE_B("NOREG"),
        .GSR("DISABLED"),
        .RESETMODE("ASYNC"),
        .ASYNC_RESET_RELEASE("ASYNC"),
        .CSDECODE_A("0b000"),
        .CSDECODE_B("0b000"),
        .WRITEMODE_A("READBEFOREWRITE"),
        .WRITEMODE_B("READBEFOREWRITE"),
        .CLKAMUX("CLKA"),
        .CLKBMUX("CLKB")
    ) stk (
        .CLKA(clk50), .CLKB(clk50),
        .WEA(we_a), .WEB(we_b),
        .CEA(1'b1), .CEB(1'b1),
        .OCEA(1'b1), .OCEB(1'b1),
        .RSTA(1'b0), .RSTB(1'b0),
        .CSA0(1'b0), .CSA1(1'b0), .CSA2(1'b0),
        .CSB0(1'b0), .CSB1(1'b0), .CSB2(1'b0),
        .ADA13(1'b0), .ADA12(1'b0),
        .ADA11(aa[7]), .ADA10(aa[6]), .ADA9(aa[5]), .ADA8(aa[4]),
        .ADA7(aa[3]), .ADA6(aa[2]), .ADA5(aa[1]), .ADA4(aa[0]),
        .ADA3(1'b0), .ADA2(1'b0), .ADA1(we_a), .ADA0(we_a),
        .ADB13(1'b0), .ADB12(1'b0),
        .ADB11(ab[7]), .ADB10(ab[6]), .ADB9(ab[5]), .ADB8(ab[4]),
        .ADB7(ab[3]), .ADB6(ab[2]), .ADB5(ab[1]), .ADB4(ab[0]),
        .ADB3(1'b0), .ADB2(1'b0), .ADB1(we_b), .ADB0(we_b),
        .DIA0(dia[0]), .DIA1(dia[1]), .DIA2(dia[2]), .DIA3(dia[3]),
        .DIA4(dia[4]), .DIA5(dia[5]), .DIA6(dia[6]), .DIA7(dia[7]),
        .DIA8(dia[8]), .DIA9(dia[9]), .DIA10(dia[10]), .DIA11(dia[11]),
        .DIA12(dia[12]), .DIA13(dia[13]), .DIA14(dia[14]), .DIA15(dia[15]),
        .DIA16(dia[16]), .DIA17(dia[17]),
        .DIB0(dib[0]), .DIB1(dib[1]), .DIB2(dib[2]), .DIB3(dib[3]),
        .DIB4(dib[4]), .DIB5(dib[5]), .DIB6(dib[6]), .DIB7(dib[7]),
        .DIB8(dib[8]), .DIB9(dib[9]), .DIB10(dib[10]), .DIB11(dib[11]),
        .DIB12(dib[12]), .DIB13(dib[13]), .DIB14(dib[14]), .DIB15(dib[15]),
        .DIB16(dib[16]), .DIB17(dib[17]),
        .DOA0(doa[0]), .DOA1(doa[1]), .DOA2(doa[2]), .DOA3(doa[3]),
        .DOA4(doa[4]), .DOA5(doa[5]), .DOA6(doa[6]), .DOA7(doa[7]),
        .DOA8(doa[8]), .DOA9(doa[9]), .DOA10(doa[10]), .DOA11(doa[11]),
        .DOA12(doa[12]), .DOA13(doa[13]), .DOA14(doa[14]), .DOA15(doa[15]),
        .DOA16(doa[16]), .DOA17(doa[17]),
        .DOB0(dob[0]), .DOB1(dob[1]), .DOB2(dob[2]), .DOB3(dob[3]),
        .DOB4(dob[4]), .DOB5(dob[5]), .DOB6(dob[6]), .DOB7(dob[7]),
        .DOB8(dob[8]), .DOB9(dob[9]), .DOB10(dob[10]), .DOB11(dob[11]),
        .DOB12(dob[12]), .DOB13(dob[13]), .DOB14(dob[14]), .DOB15(dob[15]),
        .DOB16(dob[16]), .DOB17(dob[17])
    );

    cd16 cpu (
        .reset(cpu_reset),
        .clk(clk25),
        .hold(hold),
        .irq(int),
        .ya(ya),
        .yb(yb),
        .ia(ia),
        .ib(ib),
        .aa(aa),
        .ab(ab),
        .wa(wa),
        .wb(wb),
        .ra(ra),
        .rb(rb),
        .py(py),
        .pi(pi),
        .pa(pa),
        .pbank(pbank),
        .wp(wp),
        .dy(dy),
        .di(di),
        .da(da),
        .wd(wd),
        .rd(rd),
        .CPA(16'h0000),
        .CPO(16'h0000),
        .CPctrl(),
        .t_P(),
        .t_IR(),
        .t_W(),
        .t_SP(),
        .t_RP(),
        .t_cv()
    );
endmodule

`default_nettype wire
