\ fsoc/blinky.4th — emit build dir from rtl/*.v (path 2: RTL files only)

variable b-dir-a
variable b-dir-u
variable cp-src-a
variable cp-src-u
variable bq-buf
variable bq-len
variable bq-port-a
variable bq-port-u

: blinky-join ( c-addr-name u - c-addr u )
    b-dir-a @ b-dir-u @ 2swap fsoc-append ;

variable cp-dst-a
variable cp-dst-u
variable cp-mid-a
variable cp-mid-u

: blinky-cp ( c-addr-src u c-addr-dst-name u - )
    2swap cp-src-u ! cp-src-a !
    blinky-join cp-dst-u ! cp-dst-a !
    s" cp -f " cp-src-a @ cp-src-u @ fsoc-append
    cp-mid-u ! cp-mid-a !
    cp-mid-a @ cp-mid-u @ s"  " fsoc-append
    cp-mid-a @ cp-mid-u @ fsoc-str-free
    cp-mid-u ! cp-mid-a !
    cp-mid-a @ cp-mid-u @ cp-dst-a @ cp-dst-u @ fsoc-append
    cp-mid-a @ cp-mid-u @ fsoc-str-free
    2dup system
    fsoc-str-free ;

: bq-put ( c-addr u - )
    bq-buf @ bq-len @ 2swap fsoc-append
    bq-buf @ bq-len @ fsoc-str-free
    bq-len ! bq-buf ! ;

: bq-nl ( - ) s\" \n" bq-put ;

\ Pins from board resource; -to uses logical RTL port (clk / led)
: blinky-qsf-pin ( c-addr-res u index c-addr-port u - )
    bq-port-u ! bq-port-a !
    io-find
    dup 0= IF abort" blinky-qsf: missing resource" THEN
    s" set_location_assignment PIN_" bq-put
    io.pins$ @ fsoc-fetch bq-put
    s"  -to " bq-put
    bq-port-a @ bq-port-u @ bq-put
    bq-nl ;

: blinky-write-qsf ( c-addr-path u - )
    s" # generated by fsoc — blinky (ports clk/led)" fsoc-str-dup
    bq-len ! bq-buf !
    bq-nl
    s" set_global_assignment -name FAMILY Cyclone IV E" bq-put bq-nl
    s" set_global_assignment -name DEVICE " bq-put
    plat.device@ bq-put bq-nl
    s" set_global_assignment -name TOP_LEVEL_ENTITY blinky" bq-put bq-nl
    s" set_global_assignment -name VERILOG_FILE blinky.v" bq-put bq-nl
    s" clk50" 0 s" clk" blinky-qsf-pin
    s" user_led" 0 s" led" blinky-qsf-pin
    bq-buf @ bq-len @ fsoc-write-file ;

: blinky-write-sdc ( c-addr-path u - )
    s\" create_clock -name clk -period 20.000 [get_ports {clk}]\n"
    fsoc-write-file ;

: blinky-write-build-sh ( c-addr-path u - )
    s\" #!/bin/sh\nset -e\nquartus_map blinky\nquartus_fit blinky\nquartus_asm blinky\necho quartus build done\n"
    fsoc-write-file ;

: blinky-write-load-sh ( c-addr-path u - )
    s\" #!/bin/sh\nset -e\nquartus_pgm -m jtag -o p;blinky.sof\n"
    fsoc-write-file ;

: blinky-write-sim-sh ( c-addr-path u - )
    s\" #!/bin/sh\nset -e\niverilog -o tb blinky.v tb.v\nvvp tb\n"
    fsoc-write-file ;

: blinky-write-lint-sh ( c-addr-path u - )
    s\" #!/bin/sh\nset -e\nverilator --lint-only blinky.v\n"
    fsoc-write-file ;

: blinky-emit-dir ( c-addr-dir u - )
    b-dir-u ! b-dir-a !
    s" mkdir -p " b-dir-a @ b-dir-u @ fsoc-append
    2dup system
    fsoc-str-free
    blinky-rtl@ s" /blinky.v" blinky-cp
    blinky-tb@ s" /tb.v" blinky-cp
    s" /sim.sh" blinky-join blinky-write-sim-sh
    s" /lint.sh" blinky-join blinky-write-lint-sh
    s" /blinky.qsf" blinky-join blinky-write-qsf
    s" /blinky.sdc" blinky-join blinky-write-sdc
    s" /build.sh" blinky-join blinky-write-build-sh
    s" /load.sh" blinky-join blinky-write-load-sh ;
