\ targets/quartus.4th — Quartus project files.
\ The task sets the project name, top, verilog file, clock, and
\ resource→port maps. This file does not name a task or a board.
\ Included from fsoc/toolchains/quartus.4th (after platform.4th).

variable qp-a
variable qp-u
variable qt-a
variable qt-u
variable qv-a
variable qv-u
variable qc-a
variable qc-u
variable qper-a
variable qper-u
variable qpin-buf
variable qpin-len

: quartus-project ( c-addr u - )  qp-u ! qp-a ! ;
: quartus-top ( c-addr u - )  qt-u ! qt-a ! ;
: quartus-vfile ( c-addr u - )  qv-u ! qv-a ! ;
: quartus-clock ( c-addr-name u c-addr-period u - )
    qper-u ! qper-a !  qc-u ! qc-a ! ;

: qpin-put ( c-addr u - )
    qpin-len @ 0= IF
        fsoc-str-dup qpin-len ! qpin-buf !
    ELSE
        qpin-buf @ qpin-len @ 2swap fsoc-append
        qpin-buf @ qpin-len @ fsoc-str-free
        qpin-len ! qpin-buf !
    THEN ;

\ Board resource index → RTL port. Board must already be loaded.
: quartus-map ( c-addr-res u index c-addr-port u - )
    >r >r
    io-find
    dup 0= IF abort" quartus-map: missing resource" THEN
    s" set_location_assignment PIN_" qpin-put
    io.pins$ @ fsoc-fetch qpin-put
    s"  -to " qpin-put
    r> r> qpin-put
    s\" \n" qpin-put ;

variable qf-buf
variable qf-len
variable qdir-a
variable qdir-u

: qf-put ( c-addr u - )
    qf-buf @ qf-len @ 2swap fsoc-append
    qf-buf @ qf-len @ fsoc-str-free
    qf-len ! qf-buf ! ;

: quartus-write ( c-addr-dir u - )
    qp-u @ 0= IF abort" quartus-write: no project" THEN
    qt-u @ 0= IF abort" quartus-write: no top" THEN
    qv-u @ 0= IF abort" quartus-write: no verilog file" THEN
    qc-u @ 0= IF abort" quartus-write: no clock" THEN
    qdir-u ! qdir-a !
    s" # generated by fsoc" fsoc-str-dup qf-len ! qf-buf !
    s\" \n" qf-put
    s" set_global_assignment -name FAMILY Cyclone IV E" qf-put s\" \n" qf-put
    s" set_global_assignment -name DEVICE " qf-put
    plat.device@ qf-put s\" \n" qf-put
    s" set_global_assignment -name TOP_LEVEL_ENTITY " qf-put
    qt-a @ qt-u @ qf-put s\" \n" qf-put
    s" set_global_assignment -name VERILOG_FILE " qf-put
    qv-a @ qv-u @ qf-put s\" \n" qf-put
    qpin-len @ IF qpin-buf @ qpin-len @ qf-put THEN
    qdir-a @ qdir-u @ s" /" fsoc-append qp-a @ qp-u @ fsoc-append s" .qsf" fsoc-append
    qf-buf @ qf-len @ fsoc-write-file
    qdir-a @ qdir-u @ s" /" fsoc-append qp-a @ qp-u @ fsoc-append s" .sdc" fsoc-append
    s" create_clock -name " qc-a @ qc-u @ fsoc-append
    s"  -period " fsoc-append qper-a @ qper-u @ fsoc-append
    s"  [get_ports {" fsoc-append qc-a @ qc-u @ fsoc-append
    s\" }]\n" fsoc-append
    fsoc-write-file
    qdir-a @ qdir-u @ s" /build.sh" fsoc-append
    s\" #!/bin/sh\nset -e\nquartus_map " qp-a @ qp-u @ fsoc-append
    s\" \nquartus_fit " fsoc-append qp-a @ qp-u @ fsoc-append
    s\" \nquartus_asm " fsoc-append qp-a @ qp-u @ fsoc-append
    s\" \necho quartus build done\n" fsoc-append
    fsoc-write-file
    qdir-a @ qdir-u @ s" /load.sh" fsoc-append
    s\" #!/bin/sh\nset -e\nquartus_pgm -m jtag -o p;" qp-a @ qp-u @ fsoc-append
    s\" .sof\n" fsoc-append
    fsoc-write-file
    qpin-len @ IF qpin-buf @ qpin-len @ fsoc-str-free THEN
    0 qpin-len !  0 qpin-buf !
    qf-buf @ qf-len @ fsoc-str-free
    0 qf-len ! ;
