\ targets/quartus.4th — Quartus target.
\ The task names the project, top, verilog file, clock, and maps
\ board resources to RTL ports. This file writes <project>.qsf, .sdc,
\ build.sh and load.sh into the project directory. It does not name a
\ task or a board; family and device come from the loaded platform.

variable qproj$
variable qtop$
variable qvfile$
variable qclk$
variable qperiod$
variable qmaps

ulist-new qmaps !

\ One binding of a board pin to an RTL port. Both emitters format it.
begin-structure qmap%
    field: qmap.pin$
    field: qmap.port$
    field: qmap.iostd$
end-structure

: qmap-free ( map - )
    dup qmap.pin$ @ fsoc-free
    dup qmap.port$ @ fsoc-free
    dup qmap.iostd$ @ fsoc-free
    free throw ;

: qmap-store ( pin-a pin-u port-a port-u std-a std-u - map )
    qmap% allocate throw >r
    fsoc-store r@ qmap.iostd$ !
    fsoc-store r@ qmap.port$ !
    fsoc-store r@ qmap.pin$ !
    r> ;

: quartus-reset ( - )
    qproj$ @ fsoc-free 0 qproj$ !
    qtop$ @ fsoc-free 0 qtop$ !
    qvfile$ @ fsoc-free 0 qvfile$ !
    qclk$ @ fsoc-free 0 qclk$ !
    qperiod$ @ fsoc-free 0 qperiod$ !
    ['] qmap-free qmaps @ ulist-each
    qmaps @ ulist-clear ;

: quartus-project ( c-addr u - ) qproj$ fsoc-store! ;
: quartus-top ( c-addr u - ) qtop$ fsoc-store! ;
: quartus-vfile ( c-addr u - ) qvfile$ fsoc-store! ;
: quartus-clock ( c-addr-name u c-addr-period u - )
    qperiod$ fsoc-store! qclk$ fsoc-store! ;

\ Top from the top-module file the design generator wrote. vfile is <top>.v.
: quartus-top-from-file ( c-addr-path u - )
    fsoc-read-line1
    dup 0= IF true abort" top-module empty" THEN
    2dup quartus-top
    s" .v" fsoc-cat+
    2dup quartus-vfile
    fjson.str-free ;

variable qm-pa
variable qm-pu
variable qm-ia
variable qm-iu

\ Board resource index → RTL port. Pin, port, and iostd stay on the record.
: quartus-map ( res-a res-u index port-a port-u - )
    qm-pu ! qm-pa !
    io-find
    dup 0= IF abort" quartus-map: missing resource" THEN
    dup io.iostd$ @ fsoc-fetch qm-iu ! qm-ia !
    io.pins$ @ fsoc-fetch
    qm-pa @ qm-pu @
    qm-ia @ qm-iu @
    qmap-store
    qmaps @ ulist-add ;

variable qsub-a
variable qsub-u
variable qsub-r

: qsub-match ( sub -- )
    dup sub.name$ @ fsoc-fetch qsub-a @ qsub-u @ compare 0= IF
        qsub-r !
    ELSE drop THEN ;

: io-sub-find ( io name-a name-u -- sub|0 )
    qsub-u ! qsub-a !
    0 qsub-r !
    io.subs @ ['] qsub-match swap ulist-each
    qsub-r @ ;

variable qs-ra
variable qs-ru
variable qs-sa
variable qs-su
variable qs-pa
variable qs-pu
variable qs-idx

: quartus-map-sub ( res-a res-u index sub-a sub-u port-a port-u -- )
    qs-pu ! qs-pa !
    qs-su ! qs-sa !
    qs-idx !
    qs-ru ! qs-ra !
    qs-ra @ qs-ru @ qs-idx @ io-find
    dup 0= IF abort" quartus-map-sub: missing resource" THEN
    dup io.iostd$ @ fsoc-fetch { std-a std-u }
    qs-sa @ qs-su @ io-sub-find
    dup 0= IF abort" quartus-map-sub: missing subsignal" THEN
    sub.pins$ @ fsoc-fetch
    qs-pa @ qs-pu @
    std-a std-u
    qmap-store
    qmaps @ ulist-add ;

variable qmap-cur

\ No locals: ulist-each keeps an xt on the return stack.
: qmap-emit ( map - )
    qmap-cur !
    s" set_location_assignment PIN_"
    qmap-cur @ qmap.pin$ @ fsoc-fetch fjson.str-concat
    s"  -to " fsoc-cat+
    qmap-cur @ qmap.port$ @ fsoc-fetch fsoc-cat+
    fsoc-emit-free ;

variable qmaps-xt

\ Insertion order. ulist-each keeps an xt on the return stack, and the
\ string words cannot run under that.
: qmaps-do ( xt - )
    qmaps-xt !
    qmaps @ ulist-len
    begin dup while
        1-
        dup qmaps @ ulist-nth-addr
        qmaps-xt @ execute
    repeat
    drop ;

: quartus-qsf ( c-addr-path u - )
    fjson.emit-to-file
    s" # generated by fsoc" fsoc-emit-line
    s" set_global_assignment -name FAMILY " fjson.emit plat.family@ fsoc-emit-line
    s" set_global_assignment -name DEVICE " fjson.emit plat.device@ fsoc-emit-line
    s" set_global_assignment -name TOP_LEVEL_ENTITY " fjson.emit qtop$ @ fsoc-fetch fsoc-emit-line
    s" set_global_assignment -name VERILOG_FILE " fjson.emit qvfile$ @ fsoc-fetch fsoc-emit-line
    ['] qmap-emit qmaps-do
    fsoc-emit-close ;

: quartus-sdc ( c-addr-path u - )
    fjson.emit-to-file
    s" create_clock -name " fjson.emit qclk$ @ fsoc-fetch fjson.emit
    s"  -period " fjson.emit qperiod$ @ fsoc-fetch fjson.emit
    s"  [get_ports {" fjson.emit qclk$ @ fsoc-fetch fjson.emit
    s" }]" fsoc-emit-line
    fsoc-emit-close ;

: quartus-build-sh ( c-addr-path u - )
    fjson.emit-to-file
    s" #!/bin/sh" fsoc-emit-line
    s" set -e" fsoc-emit-line
    s" quartus_map " fjson.emit qproj$ @ fsoc-fetch fsoc-emit-line
    s" quartus_fit " fjson.emit qproj$ @ fsoc-fetch fsoc-emit-line
    s" quartus_asm " fjson.emit qproj$ @ fsoc-fetch fsoc-emit-line
    s" echo quartus build done" fsoc-emit-line
    fsoc-emit-close ;

: quartus-load-sh ( c-addr-path u - )
    fjson.emit-to-file
    s" #!/bin/sh" fsoc-emit-line
    s" set -e" fsoc-emit-line
    s" quartus_pgm -m jtag -o p;" fjson.emit qproj$ @ fsoc-fetch fjson.emit
    s" .sof" fsoc-emit-line
    fsoc-emit-close ;

: quartus-check ( - )
    qproj$ @ 0= IF true abort" quartus: no project" THEN
    qtop$ @ 0= IF true abort" quartus: no top" THEN
    qvfile$ @ 0= IF true abort" quartus: no verilog file" THEN
    qclk$ @ 0= IF true abort" quartus: no clock" THEN
    current-platform @ 0= IF true abort" quartus: no board" THEN
    plat.family@ nip 0= IF true abort" quartus: board has no family" THEN ;

\ Writes <project>.qsf, <project>.sdc, build.sh, load.sh into the project dir.
: quartus-emit ( project - )
    quartus-check
    >r
    qproj$ @ fsoc-fetch s" .qsf" fjson.str-concat r@ project.file
    2dup quartus-qsf fjson.str-free
    qproj$ @ fsoc-fetch s" .sdc" fjson.str-concat r@ project.file
    2dup quartus-sdc fjson.str-free
    s" build.sh" r@ project.file 2dup quartus-build-sh fjson.str-free
    s" load.sh" r> project.file 2dup quartus-load-sh fjson.str-free
    quartus-reset ;

\ Synthesis runs on the user's side; --build only writes the files.
: quartus-run ( project - ) drop ;

\ quartus_pgm errors stay visible.
: quartus-load ( project - )
    drop s" sh load.sh" s" load.sh failed" sh-run ;

s" quartus" ' quartus-emit ' quartus-run ' quartus-load target-register
